export const DUMMY_EXHIBITION: Exhibition[] = [
  {
    id: 'exhibition1',
    title: '현대 미술 전시회',
    description: '현대 미술의 아름다움을 경험하세요.',
    displayStartDate: '2023-11-01',
    displayEndDate: '2023-11-15',
    imageUrl: 'https://example.com/exhibition1.jpg',
    isPublished: true,
    isUsed: true,
    createdBy: 'admin1',
    createdDate: '2023-10-16',
    lastModifiedBy: 'admin1',
  },
  {
    id: 'exhibition2',
    title: '고전 음악 콘서트',
    description: '클래식 음악의 아름다움을 느껴보세요.',
    displayStartDate: '2023-12-05',
    displayEndDate: '2023-12-10',
    imageUrl: 'https://example.com/exhibition2.jpg',
    isPublished: true,
    isUsed: true,
    createdBy: 'admin1',
    createdDate: '2023-10-16',
    lastModifiedBy: '',
  },
  {
    id: 'exhibition3',
    title: '사진 전시회',
    description: '미국의 명작 사진가들의 작품 전시.',
    displayStartDate: '2024-01-10',
    displayEndDate: '2024-01-25',
    imageUrl: 'https://example.com/exhibition3.jpg',
    isPublished: true,
    isUsed: true,
    createdBy: 'admin2',
    createdDate: '2023-10-16',
    lastModifiedBy: '',
  },
  {
    id: 'exhibition4',
    title: '현대 미술 작품 소개',
    description: '미술 작품들의 창조적인 세계.',
    displayStartDate: '2024-02-15',
    displayEndDate: '2024-03-05',
    imageUrl: 'https://example.com/exhibition4.jpg',
    isPublished: true,
    isUsed: true,
    createdBy: 'admin2',
    createdDate: '2023-10-16',
    lastModifiedBy: 'admin2',
  },
  {
    id: 'exhibition5',
    title: '음악 페스티벌',
    description: '다양한 음악 장르를 즐겨보세요.',
    displayStartDate: '2024-04-20',
    displayEndDate: '2024-04-25',
    imageUrl: 'https://example.com/exhibition5.jpg',
    isPublished: true,
    isUsed: true,
    createdBy: 'admin3',
    createdDate: '2023-10-16',
    lastModifiedBy: '',
  },
  {
    id: 'exhibition6',
    title: '고전 음악 특별 공연',
    description: '클래식 음악의 아름다움을 느껴보세요.',
    displayStartDate: '2024-05-10',
    displayEndDate: '2024-05-15',
    imageUrl: 'https://example.com/exhibition6.jpg',
    isPublished: true,
    isUsed: true,
    createdBy: 'admin4',
    createdDate: '2023-10-16',
    lastModifiedBy: 'admin4',
  },
  {
    id: 'exhibition7',
    title: '미술 감상 및 토론',
    description: '미술에 대한 흥미로운 토론 및 감상.',
    displayStartDate: '2024-06-10',
    displayEndDate: '2024-06-25',
    imageUrl: 'https://example.com/exhibition7.jpg',
    isPublished: true,
    isUsed: true,
    createdBy: 'admin5',
    createdDate: '2023-10-16',
    lastModifiedBy: '',
  },
  {
    id: 'exhibition8',
    title: '사진작가와의 만남',
    description: '세계적인 사진 작가와의 대화와 전시.',
    displayStartDate: '2024-07-05',
    displayEndDate: '2024-07-15',
    imageUrl: 'https://example.com/exhibition8.jpg',
    isPublished: true,
    isUsed: true,
    createdBy: 'admin6',
    createdDate: '2023-10-16',
    lastModifiedBy: 'admin6',
  },
  {
    id: 'exhibition9',
    title: '현대 미술과 기술',
    description: '기술과 미술의 만남을 탐구하세요.',
    displayStartDate: '2024-08-10',
    displayEndDate: '2024-08-25',
    imageUrl: 'https://example.com/exhibition9.jpg',
    isPublished: true,
    isUsed: true,
    createdBy: 'admin7',
    createdDate: '2023-10-16',
    lastModifiedBy: '',
  },
  {
    id: 'exhibition10',
    title: '사진과 자연의 조화',
    description: '자연 속에서 담긴 아름다운 순간들.',
    displayStartDate: '2024-09-10',
    displayEndDate: '2024-09-25',
    imageUrl: 'https://example.com/exhibition10.jpg',
    isPublished: true,
    isUsed: true,
    createdBy: 'admin8',
    createdDate: '2023-10-16',
    lastModifiedBy: '',
  },
];
