import { CHART_COLORS } from './CHART_COLORS';
import { BAR_CHART_OPTIONS } from './BAR_CHART_OPTIONS';
import { DOUGHNUT_CHART_OPTIONS } from './DOUGHNUT_CHART_OPTIONS';
import { BOARD_TITLE } from './BOARD_TITLE';

export { CHART_COLORS, BAR_CHART_OPTIONS, DOUGHNUT_CHART_OPTIONS, BOARD_TITLE };
