export const DUMMY_USERS: User[] = [
  {
    id: 'jinho9357',
    password: 'password123',
    signUpMethod: 'naver',
    pushNotification: true,
    nickname: 'JinhoStar',
    name: 'Kim Jinho',
    birthDate: '1995-04-21',
    phone: '010-1234-5678',
    gender: 'male',
    signUpDate: '2023-10-03T12:15:30',
    address: 'Seoul, Gangnam-gu',
    livingInfo: {
      duration: '1-2 years',
      type: 'One-room',
      people: '1 person',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'soojin8490',
    password: 'passsoojin',
    signUpMethod: 'kakao',
    pushNotification: false,
    nickname: 'SooFly',
    name: 'Lee Soojin',
    birthDate: '1993-08-19',
    phone: '010-8742-9045',
    gender: 'female',
    signUpDate: '2023-09-21T15:45:50',
    address: 'Seoul, Jongno-gu',
    livingInfo: {
      duration: '3-4 years',
      type: 'Two-room',
      people: '2 people',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'hyunwoo7425',
    password: 'woohyuno',
    signUpMethod: 'email',
    pushNotification: true,
    nickname: 'HyunBooster',
    name: 'Park Hyunwoo',
    birthDate: '1992-12-05',
    phone: '010-7591-2265',
    gender: 'male',
    signUpDate: '2023-05-13T10:31:10',
    address: 'Seoul, Seodaemun-gu',
    livingInfo: {
      duration: '5 years or more',
      type: 'One-room',
      people: '1 person',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser3',
    password: 'password3',
    signUpMethod: 'naver',
    pushNotification: true,
    nickname: 'GeneratedUser3',
    name: 'Name3',
    birthDate: '2000-01-03',
    phone: '010-0000-0003',
    gender: 'male',
    signUpDate: '2023-01-03T15:00:00.000Z',
    address: 'Generated Address 3',
    livingInfo: {
      duration: '3-4 years',
      type: 'One-room',
      people: '1 person',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser4',
    password: 'password4',
    signUpMethod: 'kakao',
    pushNotification: false,
    nickname: 'GeneratedUser4',
    name: 'Name4',
    birthDate: '2000-01-04',
    phone: '010-0000-0004',
    gender: 'female',
    signUpDate: '2023-01-04T15:00:00.000Z',
    address: 'Generated Address 4',
    livingInfo: {
      duration: '5 years or more',
      type: 'Two-room',
      people: '2 people',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser5',
    password: 'password5',
    signUpMethod: 'email',
    pushNotification: true,
    nickname: 'GeneratedUser5',
    name: 'Name5',
    birthDate: '2000-01-05',
    phone: '010-0000-0005',
    gender: 'male',
    signUpDate: '2023-01-05T15:00:00.000Z',
    address: 'Generated Address 5',
    livingInfo: {
      duration: '5 years or more',
      type: 'Two-room',
      people: '3 or more people',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser6',
    password: 'password6',
    signUpMethod: 'naver',
    pushNotification: true,
    nickname: 'GeneratedUser6',
    name: 'Name6',
    birthDate: '2000-01-06',
    phone: '010-0000-0006',
    gender: 'male',
    signUpDate: '2023-01-06T15:00:00.000Z',
    address: 'Generated Address 6',
    livingInfo: {
      duration: '5 years or more',
      type: 'One-room',
      people: '1 person',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser7',
    password: 'password7',
    signUpMethod: 'kakao',
    pushNotification: false,
    nickname: 'GeneratedUser7',
    name: 'Name7',
    birthDate: '2000-01-07',
    phone: '010-0000-0007',
    gender: 'female',
    signUpDate: '2023-01-07T15:00:00.000Z',
    address: 'Generated Address 7',
    livingInfo: {
      duration: '5 years or more',
      type: 'Two-room',
      people: '2 people',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser8',
    password: 'password8',
    signUpMethod: 'email',
    pushNotification: true,
    nickname: 'GeneratedUser8',
    name: 'Name8',
    birthDate: '2000-01-08',
    phone: '010-0000-0008',
    gender: 'male',
    signUpDate: '2023-01-08T15:00:00.000Z',
    address: 'Generated Address 8',
    livingInfo: {
      duration: '5 years or more',
      type: 'Two-room',
      people: '3 or more people',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser9',
    password: 'password9',
    signUpMethod: 'naver',
    pushNotification: true,
    nickname: 'GeneratedUser9',
    name: 'Name9',
    birthDate: '2000-01-09',
    phone: '010-0000-0009',
    gender: 'male',
    signUpDate: '2023-01-09T15:00:00.000Z',
    address: 'Generated Address 9',
    livingInfo: {
      duration: '5 years or more',
      type: 'One-room',
      people: '1 person',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser10',
    password: 'password10',
    signUpMethod: 'kakao',
    pushNotification: false,
    nickname: 'GeneratedUser10',
    name: 'Name10',
    birthDate: '2000-01-10',
    phone: '010-0000-0010',
    gender: 'female',
    signUpDate: '2023-01-10T15:00:00.000Z',
    address: 'Generated Address 10',
    livingInfo: {
      duration: '1-2 years',
      type: 'Two-room',
      people: '2 people',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser11',
    password: 'password11',
    signUpMethod: 'email',
    pushNotification: true,
    nickname: 'GeneratedUser11',
    name: 'Name11',
    birthDate: '2000-01-11',
    phone: '010-0000-0011',
    gender: 'male',
    signUpDate: '2023-01-11T15:00:00.000Z',
    address: 'Generated Address 11',
    livingInfo: {
      duration: '1-2 years',
      type: 'Two-room',
      people: '3 or more people',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser12',
    password: 'password12',
    signUpMethod: 'naver',
    pushNotification: true,
    nickname: 'GeneratedUser12',
    name: 'Name12',
    birthDate: '2000-01-12',
    phone: '010-0000-0012',
    gender: 'male',
    signUpDate: '2023-01-12T15:00:00.000Z',
    address: 'Generated Address 12',
    livingInfo: {
      duration: '3-4 years',
      type: 'One-room',
      people: '1 person',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser13',
    password: 'password13',
    signUpMethod: 'kakao',
    pushNotification: false,
    nickname: 'GeneratedUser13',
    name: 'Name13',
    birthDate: '2000-01-13',
    phone: '010-0000-0013',
    gender: 'female',
    signUpDate: '2023-01-13T15:00:00.000Z',
    address: 'Generated Address 13',
    livingInfo: {
      duration: '3-4 years',
      type: 'Two-room',
      people: '2 people',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser14',
    password: 'password14',
    signUpMethod: 'email',
    pushNotification: true,
    nickname: 'GeneratedUser14',
    name: 'Name14',
    birthDate: '2000-01-14',
    phone: '010-0000-0014',
    gender: 'male',
    signUpDate: '2023-01-14T15:00:00.000Z',
    address: 'Generated Address 14',
    livingInfo: {
      duration: '5 years or more',
      type: 'Two-room',
      people: '3 or more people',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser15',
    password: 'password15',
    signUpMethod: 'naver',
    pushNotification: true,
    nickname: 'GeneratedUser15',
    name: 'Name15',
    birthDate: '2000-01-15',
    phone: '010-0000-0015',
    gender: 'male',
    signUpDate: '2023-01-15T15:00:00.000Z',
    address: 'Generated Address 15',
    livingInfo: {
      duration: '5 years or more',
      type: 'One-room',
      people: '1 person',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser16',
    password: 'password16',
    signUpMethod: 'kakao',
    pushNotification: false,
    nickname: 'GeneratedUser16',
    name: 'Name16',
    birthDate: '2000-01-16',
    phone: '010-0000-0016',
    gender: 'female',
    signUpDate: '2023-01-16T15:00:00.000Z',
    address: 'Generated Address 16',
    livingInfo: {
      duration: '5 years or more',
      type: 'Two-room',
      people: '2 people',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser17',
    password: 'password17',
    signUpMethod: 'email',
    pushNotification: true,
    nickname: 'GeneratedUser17',
    name: 'Name17',
    birthDate: '2000-01-17',
    phone: '010-0000-0017',
    gender: 'male',
    signUpDate: '2023-01-17T15:00:00.000Z',
    address: 'Generated Address 17',
    livingInfo: {
      duration: '5 years or more',
      type: 'Two-room',
      people: '3 or more people',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser18',
    password: 'password18',
    signUpMethod: 'naver',
    pushNotification: true,
    nickname: 'GeneratedUser18',
    name: 'Name18',
    birthDate: '2000-01-18',
    phone: '010-0000-0018',
    gender: 'male',
    signUpDate: '2023-01-18T15:00:00.000Z',
    address: 'Generated Address 18',
    livingInfo: {
      duration: '5 years or more',
      type: 'One-room',
      people: '1 person',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser19',
    password: 'password19',
    signUpMethod: 'kakao',
    pushNotification: false,
    nickname: 'GeneratedUser19',
    name: 'Name19',
    birthDate: '2000-01-19',
    phone: '010-0000-0019',
    gender: 'female',
    signUpDate: '2023-01-19T15:00:00.000Z',
    address: 'Generated Address 19',
    livingInfo: {
      duration: '5 years or more',
      type: 'Two-room',
      people: '2 people',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser20',
    password: 'password20',
    signUpMethod: 'email',
    pushNotification: true,
    nickname: 'GeneratedUser20',
    name: 'Name20',
    birthDate: '2000-01-20',
    phone: '010-0000-0020',
    gender: 'male',
    signUpDate: '2023-01-20T15:00:00.000Z',
    address: 'Generated Address 20',
    livingInfo: {
      duration: '1-2 years',
      type: 'Two-room',
      people: '3 or more people',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser21',
    password: 'password21',
    signUpMethod: 'naver',
    pushNotification: true,
    nickname: 'GeneratedUser21',
    name: 'Name21',
    birthDate: '2000-01-21',
    phone: '010-0000-0021',
    gender: 'male',
    signUpDate: '2023-01-21T15:00:00.000Z',
    address: 'Generated Address 21',
    livingInfo: {
      duration: '1-2 years',
      type: 'One-room',
      people: '1 person',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser22',
    password: 'password22',
    signUpMethod: 'kakao',
    pushNotification: false,
    nickname: 'GeneratedUser22',
    name: 'Name22',
    birthDate: '2000-01-22',
    phone: '010-0000-0022',
    gender: 'female',
    signUpDate: '2023-01-22T15:00:00.000Z',
    address: 'Generated Address 22',
    livingInfo: {
      duration: '3-4 years',
      type: 'Two-room',
      people: '2 people',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser23',
    password: 'password23',
    signUpMethod: 'email',
    pushNotification: true,
    nickname: 'GeneratedUser23',
    name: 'Name23',
    birthDate: '2000-01-23',
    phone: '010-0000-0023',
    gender: 'male',
    signUpDate: '2023-01-23T15:00:00.000Z',
    address: 'Generated Address 23',
    livingInfo: {
      duration: '3-4 years',
      type: 'Two-room',
      people: '3 or more people',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser24',
    password: 'password24',
    signUpMethod: 'naver',
    pushNotification: true,
    nickname: 'GeneratedUser24',
    name: 'Name24',
    birthDate: '2000-01-24',
    phone: '010-0000-0024',
    gender: 'male',
    signUpDate: '2023-01-24T15:00:00.000Z',
    address: 'Generated Address 24',
    livingInfo: {
      duration: '5 years or more',
      type: 'One-room',
      people: '1 person',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser25',
    password: 'password25',
    signUpMethod: 'kakao',
    pushNotification: false,
    nickname: 'GeneratedUser25',
    name: 'Name25',
    birthDate: '2000-01-25',
    phone: '010-0000-0025',
    gender: 'female',
    signUpDate: '2023-01-25T15:00:00.000Z',
    address: 'Generated Address 25',
    livingInfo: {
      duration: '5 years or more',
      type: 'Two-room',
      people: '2 people',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser26',
    password: 'password26',
    signUpMethod: 'email',
    pushNotification: true,
    nickname: 'GeneratedUser26',
    name: 'Name26',
    birthDate: '2000-01-26',
    phone: '010-0000-0026',
    gender: 'male',
    signUpDate: '2023-01-26T15:00:00.000Z',
    address: 'Generated Address 26',
    livingInfo: {
      duration: '5 years or more',
      type: 'Two-room',
      people: '3 or more people',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser27',
    password: 'password27',
    signUpMethod: 'naver',
    pushNotification: true,
    nickname: 'GeneratedUser27',
    name: 'Name27',
    birthDate: '2000-01-27',
    phone: '010-0000-0027',
    gender: 'male',
    signUpDate: '2023-01-27T15:00:00.000Z',
    address: 'Generated Address 27',
    livingInfo: {
      duration: '5 years or more',
      type: 'One-room',
      people: '1 person',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser28',
    password: 'password28',
    signUpMethod: 'kakao',
    pushNotification: false,
    nickname: 'GeneratedUser28',
    name: 'Name28',
    birthDate: '2000-01-28',
    phone: '010-0000-0028',
    gender: 'female',
    signUpDate: '2023-01-28T15:00:00.000Z',
    address: 'Generated Address 28',
    livingInfo: {
      duration: '5 years or more',
      type: 'Two-room',
      people: '2 people',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser29',
    password: 'password29',
    signUpMethod: 'email',
    pushNotification: true,
    nickname: 'GeneratedUser29',
    name: 'Name29',
    birthDate: '2000-01-29',
    phone: '010-0000-0029',
    gender: 'male',
    signUpDate: '2023-01-29T15:00:00.000Z',
    address: 'Generated Address 29',
    livingInfo: {
      duration: '5 years or more',
      type: 'Two-room',
      people: '3 or more people',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser30',
    password: 'password30',
    signUpMethod: 'naver',
    pushNotification: true,
    nickname: 'GeneratedUser30',
    name: 'Name30',
    birthDate: '2000-01-30',
    phone: '010-0000-0030',
    gender: 'male',
    signUpDate: '2023-01-30T15:00:00.000Z',
    address: 'Generated Address 30',
    livingInfo: {
      duration: '1-2 years',
      type: 'One-room',
      people: '1 person',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser31',
    password: 'password31',
    signUpMethod: 'kakao',
    pushNotification: false,
    nickname: 'GeneratedUser31',
    name: 'Name31',
    birthDate: '2000-01-31',
    phone: '010-0000-0031',
    gender: 'female',
    signUpDate: '2023-01-31T15:00:00.000Z',
    address: 'Generated Address 31',
    livingInfo: {
      duration: '1-2 years',
      type: 'Two-room',
      people: '2 people',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser32',
    password: 'password32',
    signUpMethod: 'email',
    pushNotification: true,
    nickname: 'GeneratedUser32',
    name: 'Name32',
    birthDate: '2000-02-01',
    phone: '010-0000-0032',
    gender: 'male',
    signUpDate: '2023-02-01T15:00:00.000Z',
    address: 'Generated Address 32',
    livingInfo: {
      duration: '3-4 years',
      type: 'Two-room',
      people: '3 or more people',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser33',
    password: 'password33',
    signUpMethod: 'naver',
    pushNotification: true,
    nickname: 'GeneratedUser33',
    name: 'Name33',
    birthDate: '2000-02-02',
    phone: '010-0000-0033',
    gender: 'male',
    signUpDate: '2023-02-02T15:00:00.000Z',
    address: 'Generated Address 33',
    livingInfo: {
      duration: '3-4 years',
      type: 'One-room',
      people: '1 person',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser34',
    password: 'password34',
    signUpMethod: 'kakao',
    pushNotification: false,
    nickname: 'GeneratedUser34',
    name: 'Name34',
    birthDate: '2000-02-03',
    phone: '010-0000-0034',
    gender: 'female',
    signUpDate: '2023-02-03T15:00:00.000Z',
    address: 'Generated Address 34',
    livingInfo: {
      duration: '5 years or more',
      type: 'Two-room',
      people: '2 people',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser35',
    password: 'password35',
    signUpMethod: 'email',
    pushNotification: true,
    nickname: 'GeneratedUser35',
    name: 'Name35',
    birthDate: '2000-02-04',
    phone: '010-0000-0035',
    gender: 'male',
    signUpDate: '2023-02-04T15:00:00.000Z',
    address: 'Generated Address 35',
    livingInfo: {
      duration: '5 years or more',
      type: 'Two-room',
      people: '3 or more people',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser36',
    password: 'password36',
    signUpMethod: 'naver',
    pushNotification: true,
    nickname: 'GeneratedUser36',
    name: 'Name36',
    birthDate: '2000-02-05',
    phone: '010-0000-0036',
    gender: 'male',
    signUpDate: '2023-02-05T15:00:00.000Z',
    address: 'Generated Address 36',
    livingInfo: {
      duration: '5 years or more',
      type: 'One-room',
      people: '1 person',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser37',
    password: 'password37',
    signUpMethod: 'kakao',
    pushNotification: false,
    nickname: 'GeneratedUser37',
    name: 'Name37',
    birthDate: '2000-02-06',
    phone: '010-0000-0037',
    gender: 'female',
    signUpDate: '2023-02-06T15:00:00.000Z',
    address: 'Generated Address 37',
    livingInfo: {
      duration: '5 years or more',
      type: 'Two-room',
      people: '2 people',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser38',
    password: 'password38',
    signUpMethod: 'email',
    pushNotification: true,
    nickname: 'GeneratedUser38',
    name: 'Name38',
    birthDate: '2000-02-07',
    phone: '010-0000-0038',
    gender: 'male',
    signUpDate: '2023-02-07T15:00:00.000Z',
    address: 'Generated Address 38',
    livingInfo: {
      duration: '5 years or more',
      type: 'Two-room',
      people: '3 or more people',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser39',
    password: 'password39',
    signUpMethod: 'naver',
    pushNotification: true,
    nickname: 'GeneratedUser39',
    name: 'Name39',
    birthDate: '2000-02-08',
    phone: '010-0000-0039',
    gender: 'male',
    signUpDate: '2023-02-08T15:00:00.000Z',
    address: 'Generated Address 39',
    livingInfo: {
      duration: '5 years or more',
      type: 'One-room',
      people: '1 person',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser40',
    password: 'password40',
    signUpMethod: 'kakao',
    pushNotification: false,
    nickname: 'GeneratedUser40',
    name: 'Name40',
    birthDate: '2000-02-09',
    phone: '010-0000-0040',
    gender: 'female',
    signUpDate: '2023-02-09T15:00:00.000Z',
    address: 'Generated Address 40',
    livingInfo: {
      duration: '1-2 years',
      type: 'Two-room',
      people: '2 people',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser41',
    password: 'password41',
    signUpMethod: 'email',
    pushNotification: true,
    nickname: 'GeneratedUser41',
    name: 'Name41',
    birthDate: '2000-02-10',
    phone: '010-0000-0041',
    gender: 'male',
    signUpDate: '2023-02-10T15:00:00.000Z',
    address: 'Generated Address 41',
    livingInfo: {
      duration: '1-2 years',
      type: 'Two-room',
      people: '3 or more people',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser42',
    password: 'password42',
    signUpMethod: 'naver',
    pushNotification: true,
    nickname: 'GeneratedUser42',
    name: 'Name42',
    birthDate: '2000-02-11',
    phone: '010-0000-0042',
    gender: 'male',
    signUpDate: '2023-02-11T15:00:00.000Z',
    address: 'Generated Address 42',
    livingInfo: {
      duration: '3-4 years',
      type: 'One-room',
      people: '1 person',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser43',
    password: 'password43',
    signUpMethod: 'kakao',
    pushNotification: false,
    nickname: 'GeneratedUser43',
    name: 'Name43',
    birthDate: '2000-02-12',
    phone: '010-0000-0043',
    gender: 'female',
    signUpDate: '2023-02-12T15:00:00.000Z',
    address: 'Generated Address 43',
    livingInfo: {
      duration: '3-4 years',
      type: 'Two-room',
      people: '2 people',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser44',
    password: 'password44',
    signUpMethod: 'email',
    pushNotification: true,
    nickname: 'GeneratedUser44',
    name: 'Name44',
    birthDate: '2000-02-13',
    phone: '010-0000-0044',
    gender: 'male',
    signUpDate: '2023-02-13T15:00:00.000Z',
    address: 'Generated Address 44',
    livingInfo: {
      duration: '5 years or more',
      type: 'Two-room',
      people: '3 or more people',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser45',
    password: 'password45',
    signUpMethod: 'naver',
    pushNotification: true,
    nickname: 'GeneratedUser45',
    name: 'Name45',
    birthDate: '2000-02-14',
    phone: '010-0000-0045',
    gender: 'male',
    signUpDate: '2023-02-14T15:00:00.000Z',
    address: 'Generated Address 45',
    livingInfo: {
      duration: '5 years or more',
      type: 'One-room',
      people: '1 person',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser46',
    password: 'password46',
    signUpMethod: 'kakao',
    pushNotification: false,
    nickname: 'GeneratedUser46',
    name: 'Name46',
    birthDate: '2000-02-15',
    phone: '010-0000-0046',
    gender: 'female',
    signUpDate: '2023-02-15T15:00:00.000Z',
    address: 'Generated Address 46',
    livingInfo: {
      duration: '5 years or more',
      type: 'Two-room',
      people: '2 people',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser47',
    password: 'password47',
    signUpMethod: 'email',
    pushNotification: true,
    nickname: 'GeneratedUser47',
    name: 'Name47',
    birthDate: '2000-02-16',
    phone: '010-0000-0047',
    gender: 'male',
    signUpDate: '2023-02-16T15:00:00.000Z',
    address: 'Generated Address 47',
    livingInfo: {
      duration: '5 years or more',
      type: 'Two-room',
      people: '3 or more people',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser48',
    password: 'password48',
    signUpMethod: 'naver',
    pushNotification: true,
    nickname: 'GeneratedUser48',
    name: 'Name48',
    birthDate: '2000-02-17',
    phone: '010-0000-0048',
    gender: 'male',
    signUpDate: '2023-02-17T15:00:00.000Z',
    address: 'Generated Address 48',
    livingInfo: {
      duration: '5 years or more',
      type: 'One-room',
      people: '1 person',
    },
    postHistory: [],
    reportHistory: [],
  },
  {
    id: 'generatedUser49',
    password: 'password49',
    signUpMethod: 'kakao',
    pushNotification: false,
    nickname: 'GeneratedUser49',
    name: 'Name49',
    birthDate: '2000-02-18',
    phone: '010-0000-0049',
    gender: 'female',
    signUpDate: '2023-02-18T15:00:00.000Z',
    address: 'Generated Address 49',
    livingInfo: {
      duration: '5 years or more',
      type: 'Two-room',
      people: '2 people',
    },
    postHistory: [],
    reportHistory: [],
  },
];
