name: Manual Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.STAGING_EC2_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        with:
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.EC2_USERNAME }}
          REMOTE_PORT: ${{ secrets.EC2_PORT }}
          SOURCE: ".next/ public/"
          TARGET: "/home/ec2-user/housetalk-admin"
          SSH_PRIVATE_KEY: ${{ secrets.STAGING_EC2_SSH_PRIVATE_KEY }}

      - name: Kill Previous Node Process
        run: |
          ssh -o "BatchMode yes" -i $HOME/.ssh/id_rsa ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "pkill -f 'node .next'"

      - name: Start Next.js on EC2
        run: |
          ssh -o "BatchMode yes" -i ${{ github.workspace }}/.ssh/id_rsa ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "cd /home/ec2-user/housetalk-admin && nohup npm start > app.log 2>&1 &"
