name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to EC2
      uses: easingthemes/ssh-deploy@main
      with:
        REMOTE_HOST: ${{ secrets.EC2_HOST }}
        REMOTE_USER: ${{ secrets.EC2_USERNAME }}
        REMOTE_PORT: ${{ secrets.EC2_PORT }}
        SOURCE: "./"
        TARGET: "/path/on/your/server"
        KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
