name: Manual Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.STAGING_EC2_SSH_PRIVATE_KEY }}
          name: id_rsa # This sets the name of the private key file
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"

      - name: Set SSH Key Permissions
        run: |
          chmod 600 ${{ github.workspace }}/.ssh/id_rsa

      - name: Start Next.js on EC2
        run: |
          ssh -v -o "BatchMode yes" -i ${{ github.workspace }}/.ssh/id_rsa ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "cd /home/ec2-user/housetalk-admin && nohup npm start > app.log 2>&1 &"

      # Optional: Add a step to check the app.log if you want to ensure that the server started correctly.
      - name: Check app log
        run: |
          ssh -o "BatchMode yes" -i ${{ github.workspace }}/.ssh/id_rsa ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "cat /home/ec2-user/housetalk-admin/app.log"
